__default__:
    cpus-per-task: 1
    mem-per-cpu: 10G
    partition: PARTITION
    output: '{log.output}_cluster'
    error: '{log.error}_cluster'
    job-name: '{rule}.{wildcards}'


###### Cluster parameters for recup_stat rules ########
recup_stat :
    mem-per-cpu: 4G

###### Cluster parameters for summary_stat rules ########
summary_stat :
    mem-per-cpu: 4G

###### Cluster parameters for repeatMasker rules ########
repeatMasker :
    mem-per-cpu: 4G
    cpus-per-task: 6

###### Cluster parameters for renameFile rules ########
renameFile :
    mem-per-cpu: 4G

###### Cluster parameters for hisat2_index rules ########
hisat2_index :
    mem-per-cpu: 4G

###### Cluster parameters for hisats2_alignement rules ########
hisat2_alignement:
    mem-per-cpu: 4G
    cpus-per-task: 10
    partition: long

###### Cluster parameters for samtools rules ########
samtools :
    mem-per-cpu: 2G
    cpus-per-task: 6

 ###### Cluster parameters for merge_bam rules ########
merge_bam :
    mem-per-cpu: 4G
    cpus-per-task: 6

###### Cluster parameters for sort_bam rules ########
sort_bam :
    mem-per-cpu: 4G
    cpus-per-task: 6

###### Cluster parameters for bam2hints rules ########
bam2hints :
    mem-per-cpu: 4G
    cpus-per-task: 6

###### Cluster parameters for bam2hints_filter rules ########
bam2hints_filter :
    mem-per-cpu: 4G
    cpus-per-task: 6

###### Cluster parameters for exonerate rules ########
exonerate :
    mem-per-cpu: 4G
    cpus-per-task: 6

###### Cluster parameters for merge_hint rules ########
merge_hint:
    mem-per-cpu: 4G
    cpus-per-task: 6

###### Cluster parameters for BRAKER rules ########
BRAKER :
    mem-per-cpu: 4G
    cpus-per-task: 6

###### Cluster parameters for augustus rules ########
augustus :
    mem-per-cpu: 4G
    cpus-per-task: 6
###### Cluster parameters for merge_gff rules ########
merge_gff :
  mem: "--mem-per-cpu=4G"

###### Cluster parameters for createFasta rules ########
createFasta:
    mem-per-cpu: 4G
    cpus-per-task: 6
    partition: fast

###### Cluster parameters for busco rules ########
busco:
    mem-per-cpu: 4G
    cpus-per-task: 6

###### Cluster parameters for recuperation_Stat rules ########
recuperation_Stat:
    mem-per-cpu: 4G

###### Cluster parameters for report rules ########
report:
    mem-per-cpu: 4G
    partition: fast
